### ISSUE TITLE
Wrong redirect_uri for rocket chat running in docker container

### ISSUE THREAD

**Issue by yazynin** [heilerich/Rocket.Chat.App-Slackline#2]
When rocket chat running in container, app used localhost:3000 for redirect url, when I clicked /slackbridge login
<img width="605" alt="Screenshot 2022-04-22 at 11 54 30" src="https://user-images.githubusercontent.com/158371/164669215-6eaad773-a6a0-41b7-9124-afb139d79516.png">

**Comment by heilerich** [comment]
The plugin gets the server's URL from the RC instance. This looks like you have not correctly set the `ROOT_URL` environment variable of your RC container. Can you check that first?

**Comment by yazynin** [comment]
Yes, worked, thanks for help!
